#remote_theme: daattali/beautiful-jekyll

#theme: jekyll-theme-slate
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
- jekyll-remote-theme
