#remote_theme: daattali/beautiful-jekyll

#theme: jekyll-theme-slate //probablemente no
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
theme: jekyll-theme-primer
plugins:
- jekyll-remote-theme
