#remote_theme: daattali/beautiful-jekyll

#theme: jekyll-theme-slate //probablemente no
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer //probablemente no

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-remote-theme
