#remote_theme: daattali/beautiful-jekyll

#theme: jekyll-theme-slate //probablemente no
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer //probablemente no
theme: minimal-mistakes-jekyll
plugins:
- jekyll-remote-theme
