#remote_theme: daattali/beautiful-jekyll

#theme: jekyll-theme-slate //probablemente no
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer //probablemente no

remote_theme: "daviddarnes/alembic"
plugins:
- jekyll-remote-theme
- jekyll-include-cache
